SecuritySite/Areas/Identity/Pages/Account/ConfirmEmail.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using SecuritySite.Data;

namespace SecuritySite.Areas.Identity.Pages.Account
{
    public class ConfirmEmailModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public ConfirmEmailModel(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [TempData]
        public string StatusMessage { get; set; }
        public async Task<IActionResult> OnGetAsync(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return RedirectToPage("/Index");
            }

            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{userId}'.");
            }

            code = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(code));
            var result = await _userManager.ConfirmEmailAsync(user, code);
            StatusMessage = result.Succeeded ? "Thank you for confirming your email." : "Error confirming your email.";
            return Page();
        }
    }
}

SecuritySite/Areas/Identity/Pages/Account/Login.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using SecuritySite.Data;

namespace SecuritySite.Areas.Identity.Pages.Account
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(SignInManager<ApplicationUser> signInManager, ILogger<LoginModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [BindProperty]
        public InputModel Input { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public string ReturnUrl { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [TempData]
        public string ErrorMessage { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public class InputModel
        {
            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [EmailAddress]
            public string Email { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public async Task OnGetAsync(string returnUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            returnUrl ??= Url.Content("~/");

            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/");

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");
                    return LocalRedirect(returnUrl);
                }
                if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = Input.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    _logger.LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return Page();
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

SecuritySite/Pages/Account/Edit/Features.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SecuritySite.Models;
using SecuritySite.Services;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace SecuritySite.Pages.Account.edit
{
        [Authorize]
    public class FeaturesModel : PageModel
    {
        AccountUpdateService _update { get;set; }
        public AccountQueryService _query { get; set; }
        public FeaturesModel(AccountQueryService query, AccountUpdateService update) 
        {
            _update = update;
            _query = query;
        }

        [BindProperty(SupportsGet = true)]
        public int accountId { get; set; }
        public MonitoredAccount account { get; set; }
        public List<AccountFeature> accountFeatures { get; set; }
        public List<AccountFeature> availableFeatures { get; set; }
        public List<AccountFeature> basePlans { get;set; }
        public IActionResult OnGet()
        {
            try
            {
                if (_query.VerifyOwner(User, _query.GetMonitoredAccount(accountId)))
                {
                    account = _query.GetMonitoredAccount(accountId);
                }
            }
            catch
            {
                return RedirectToPage("error");
            }

            if (account == null)
            {
                return RedirectToPage("error");
            }
            else if (account.completed != true)
            {
                return RedirectToPage("/Account/new/Features", new {accountId = this.accountId});
            }
            accountFeatures = _query.GetFeatures(account.Features);
            availableFeatures = _query.FilterExisting( account.Features , _query.GetFeatures(account.commercial, false)).ToList();
            basePlans = _query.FilterExisting(account.Features, _query.GetFeatures(true)).ToList();

            return Page();
        }
        [BindProperty]
        public string test { get; set; }
        [BindProperty]
        public List<string> selectedFeatures { get; set; }
        public void OnPost()
        {

        }

        [BindProperty]
        public string RemoveCode { get; set; }
        public IActionResult OnPostRemoveFeature()
        {
            if (_query.VerifyOwner(User, _query.GetMonitoredAccount(accountId)))
            {
                account = _query.GetMonitoredAccount(accountId);
            }
            if (account == null)
            {
                return RedirectToPage("error");
            }
            else if (account.completed != true)
            {
                return RedirectToPage("/Account/new/Features", new { accountId = this.accountId });
            }

            AccountFeature feature = _query.GetFeature(RemoveCode);
            _update.remove_AccountFeature(account, feature);

            accountFeatures = _query.GetFeatures(account.Features);
            availableFeatures = _query.GetFeatures(account.commercial, false).ToList();
            basePlans = _query.FilterExisting(account.Features, _query.GetFeatures(true)).ToList();
            return Page();
            

        }
        [BindProperty]
        public List<string> addFeatures { get; set; }
        int x = 929;
        public IActionResult OnPostAddFeature()
        {
            if (_query.VerifyOwner(User, _query.GetMonitoredAccount(accountId)))
            {
                account = _query.GetMonitoredAccount(accountId);
            }
            if (account == null)
            {
                return RedirectToPage("error");
            }
            else if (account.completed != true)
            {
                return RedirectToPage("/Account/new/Features", new { accountId = this.accountId });
            }
            List<AccountFeature> features = _query.GetFeatures(addFeatures).ToList();

            foreach (AccountFeature feature in features)
            {
                if (feature == null) continue;
                if (feature.BasePlan)
                {
                    var oldPlan = _query.GetBasePlan(account);
                    _update.change_BasePlan(account, oldPlan, feature);

                    accountFeatures = _query.GetFeatures(account.Features);
                    availableFeatures = _query.FilterExisting(account.Features, _query.GetFeatures(account.commercial, false)).ToList();
                    basePlans = _query.FilterExisting(account.Features, _query.GetFeatures(true)).ToList();


                    return Page();
                }
            }
            _update.add_Features(account, addFeatures);

            accountFeatures = _query.GetFeatures(account.Features);
            availableFeatures = _query.FilterExisting(account.Features, _query.GetFeatures(account.commercial, false)).ToList();
            basePlans = _query.FilterExisting(account.Features, _query.GetFeatures(true)).ToList();
            return Page();
        }
    }
}

SecuritySite/Pages/Account/Edit/Location.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Identity.Client;
using SecuritySite.Models;
using SecuritySite.Services;

namespace SecuritySite.Pages.Account.Edit
{
    [Authorize]
    public class LocationModel : PageModel
    {
        public AccountQueryService _query { get; }
        public LocationModel(AccountQueryService query) 
        { 
         _query = query;
        }
        [BindProperty(SupportsGet =true)]
        public int id { get; set; }
        public MonitoredAccount LocationInfo { get; set; }
        public IActionResult OnGet()
        {
            try
            {
                if (_query.VerifyOwner(User, _query.GetMonitoredAccount(id)))
                {
                    LocationInfo = _query.GetMonitoredAccount(id);
                }
            }
            catch
            {
                return RedirectToPage("error");
            }

            if (LocationInfo == null)
            {
                return RedirectToPage("error");
            }
            else if (!LocationInfo.completed)
            {
                return RedirectToPage("/Account/new/Features", new { accountId = LocationInfo.MonitoredAccountId });
            }
            return Page();
        }
    }
}

SecuritySite/Pages/Account/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SecuritySite.Data;
using SecuritySite.Migrations;
using SecuritySite.Models;
using SecuritySite.Services;
using System.Net.Http.Headers;
using System.Security.Claims;

namespace SecuritySite.Pages.Account
{
    [Authorize]
    public class IndexModel : PageModel
    {
        public AccountQueryService _query { get; set; }
        public AccountUpdateService _update { get; set; }
        public IndexModel(AccountQueryService query, UserManager<ApplicationUser> users, AccountUpdateService update)
        {
            _query = query;
            _update = update;
        }
        public List<MonitoredAccount> MonitoredAccounts { get; set; } = new List<MonitoredAccount>();

        [BindProperty]
        public AccountInfo accountInfo { get; set; }
        public string PageView {  get; set; }
        public object pageModel { get;set; }
        public void OnGet()
        {
            var id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string guid = _query.GetAccountGuid(id);

            MonitoredAccounts = _query.GetMonitoredAccounts(guid).ToList();
            foreach(var monitoredAccount in MonitoredAccounts)
            {
                _update.update_AccountPrice(monitoredAccount);
            }
            if (!_query.GetAccountInfo(id).Completed())
            {
                PageView = "/Pages/Account/Info/_Overview.cshtml";
                pageModel = _query.GetAccountInfo(id);
            }
            else
            {
                PageView = "/Pages/Account/Info/_Locations.cshtml";
                pageModel = _query.GetMonitoredAccounts(guid).ToList();
            }
        }
        private AccountInfo account { get;set; }
        public PartialViewResult OnGetPageView(int id)
        {


            switch (id)
            {
                case 0: {
                        //List<MonitoredAccount> accounts = _query.GetMonitoredAccounts(User.FindFirstValue(ClaimTypes.NameIdentifier)).ToList();

                        account = _query.GetAccountInfo(User.FindFirstValue(ClaimTypes.NameIdentifier));
                        return Partial("Pages/Account/Info/_Overview.cshtml", account);
                    }
                case 1:
                    string guid = _query.GetAccountGuid(User.FindFirstValue(ClaimTypes.NameIdentifier));

                    List<MonitoredAccount> locations = _query.GetMonitoredAccounts(guid).ToList();


                    PageView = "/Pages/Account/Info/_Locations.cshtml";
                    pageModel = _query.GetMonitoredAccounts(guid).ToList();
                    return Partial("Pages/Account/Info/_Locations.cshtml", locations);
                case 2:
                    return Partial("Pages/Account/Info/_Invoicing.cshtml");
                case 3:
                    return Partial("Pages/Account/Info/_Notifications.cshtml");
                case 4:
                    return Partial("Pages/Account/Info/_Requests.cshtml");
                case 5:
                    return Partial("Pages/Account/Info/_Settings.cshtml");
                default:
                    return Partial("Pages/Account/Info/_Overview.cshtml");
            }

        }
        public void OnPostAccountInfo()
        {
            var id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _update.update_AccountInfo(id, accountInfo);
            PageView = "/Pages/Account/Info/_Overview.cshtml";
            pageModel = _query.GetAccountInfo(id);
        }
    }
}

SecuritySite/Pages/Account/Info/_Invoicing.cshtml
@{
}

SecuritySite/Pages/Account/Info/_Locations.cshtml
@using SecuritySite.Models;
@model List<MonitoredAccount>

<div class="locations-padding">
    <h1 class="same-line">My Locations</h1>

    @if(Model == null || Model.Count == 0)
    {
        <p>You have no accounts, start off by creating your first account.</p>
    }
    else
    {
        <div class="account-preview-grid">
            @foreach(MonitoredAccount account in Model)
            {
                <div class="account-preview">
                    <div>
                        <br/>
                        @if (!account.commercial)
                        {
                            <i class="fa-icon-preview fa-solid fa-house"></i>
                        }
                        else
                        {
                            <i class="fa-icon-preview fa-regular fa-building"></i>
                        }
                    </div>

                    <div>
                        <p class="preview-title">@account.locationName</p>
                        <p class="preview-text">@account.address</p>
                        @if (account.accepted)
                        {
                            <p class="preview-text blue" style="font-weight:bold">Account: Approved</p>
                        }
                        else
                        {
                            <p class="preview-text redish">Account: Pending Approval</p>
                        }
                        @if (account.completed)
                        {
                            <p class="preview-text blue" style="font-weight:bold">Account Completed</p>
                        }
                        else
                        {
                            <p class="preview-text redish">Needs Review</p>
                        }
                        @if (account.deleted)
                        {
                            <p class ="preview-text redish">Delete Requested</p>
                        }
                        <p class="preview-text">Monthly Rate: $@(account.MonthlyCost)</p>
                    </div>

                    <div>
                        <a href="/Account/edit/location/@account.MonitoredAccountId">View Account</a>
                        <br />
                        <br/>
                        <a href="/Account/edit/features/@account.MonitoredAccountId">Edit Plan</a>

                    </div>
                </div>
            }
        </div>
    }



    <a href="/account/new/location" class="new-location">New Location</a>
</div>

SecuritySite/Pages/Account/Info/_Notifications.cshtml
@{
}

SecuritySite/Pages/Account/Info/_Overview.cshtml
@using SecuritySite.Models;
@model AccountInfo
<h1 class="left-margin blue">@Model.Name</h1>
<form asp-page="/Account/Index">

<div class="left-padding overview-grid">
        @*General Info*@

       
        <div>
            <br/>
            <p>Monitored Accounts: @Model.Accounts</p>
        </div>
        <div>
            <p>Email:</p>
            <input type="text" value="@Model.Email" id="accountInfo_Email" name="accountInfo.Email" />
        </div>

        <div>
            <p>Phone Number: </p>
            <input type="text" value="@Model.PhoneNumber" id="accountInfo_PhoneNumber" name="accountInfo.PhoneNumber" />
        </div>
        <div>
            <p>Billing address:</p>
            <input type="text" value="@Model.Address" id="accountInfo_Address" name="accountInfo.Address" />
        </div>

        <div>
            <p>City:</p>
            <input type="text" value="@Model.City" id="accountInfo_City" name="accountInfo.City" />
        </div>
        <div>
            <p>County:</p>
            <input type="text" value="@Model.County" id="accountInfo_County" name="accountInfo.County" />
        </div>

        <div>
            <p>Zipcode:</p>
            <input type="text" value="@Model.ZipCode" id="accountInfo_ZipCode" name="accountInfo.ZipCode" />
        </div>
        <div>
            <p>State:</p>
            <input type="text" value="@Model.State" id="accountInfo_State" name="accountInfo.State" />
        </div>


    </div>
    <p class="left-margin">Submit edits below</p>
    <button class="left-margin submit" type="submit" asp-page-handler="AccountInfo">Update</button>

</form>









@*     <br/>
<div class="left-padding billing-summary">
    @*Summarized Billing Info
        <p>Current Monthly Cost: $@(Model.MonthlyCost)</p>
        <p>Last Months Bill: $@(Model.LastBill)</p>
        <p>Next Billing Date: @Model.BillDate.ToShortDateString()</p>
    </div>


<div class="invoice-padding">
    <h1>Latest Invoice</h1>
    @if (Model.Invoice !=null)
    {
        <div class="invoice-grid">
            @*Latest Invoice
            <div>
                <p>Bill To: @(Model.Invoice.Name)</p>
                <p>Accounts: @Model.Invoice.Accounts</p>
                <p>Billing Address: @Model.Invoice.Address</p>
            </div>

            <div>
                <p class="center-content">Charged To:<br /><br /> XXXX@(Model.Invoice.CardEnding)</p>
            </div>

            <div>
                <p class="center-content">Charged:<br /><br /> $@(Model.Invoice.Price)</p>
            </div>

        </div>
        <a class="view-invoice">View Full</a>
    }


</div> *@

SecuritySite/Pages/Account/Info/_Requests.cshtml
@{
}

SecuritySite/Pages/Account/Info/_Settings.cshtml
@{
}