SecuritySite/Areas/Identity/Pages/Account/ConfirmEmail.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using SecuritySite.Data;

namespace SecuritySite.Areas.Identity.Pages.Account
{
    public class ConfirmEmailModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public ConfirmEmailModel(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [TempData]
        public string StatusMessage { get; set; }
        public async Task<IActionResult> OnGetAsync(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return RedirectToPage("/Index");
            }

            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{userId}'.");
            }

            code = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(code));
            var result = await _userManager.ConfirmEmailAsync(user, code);
            StatusMessage = result.Succeeded ? "Thank you for confirming your email." : "Error confirming your email.";
            return Page();
        }
    }
}

SecuritySite/Areas/Identity/Pages/Account/Login.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using SecuritySite.Data;

namespace SecuritySite.Areas.Identity.Pages.Account
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(SignInManager<ApplicationUser> signInManager, ILogger<LoginModel> logger)
        {
            _signInManager = signInManager;
            _logger = logger;
        }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [BindProperty]
        public InputModel Input { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public string ReturnUrl { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        [TempData]
        public string ErrorMessage { get; set; }

        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public class InputModel
        {
            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [EmailAddress]
            public string Email { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Required]
            [DataType(DataType.Password)]
            public string Password { get; set; }

            /// <summary>
            ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
            ///     directly from your code. This API may change or be removed in future releases.
            /// </summary>
            [Display(Name = "Remember me?")]
            public bool RememberMe { get; set; }
        }

        public async Task OnGetAsync(string returnUrl = null)
        {
            if (!string.IsNullOrEmpty(ErrorMessage))
            {
                ModelState.AddModelError(string.Empty, ErrorMessage);
            }

            returnUrl ??= Url.Content("~/");

            // Clear the existing external cookie to ensure a clean login process
            await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/");

            ExternalLogins = (await _signInManager.GetExternalAuthenticationSchemesAsync()).ToList();

            if (ModelState.IsValid)
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, set lockoutOnFailure: true
                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    _logger.LogInformation("User logged in.");
                    return LocalRedirect(returnUrl);
                }
                if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = Input.RememberMe });
                }
                if (result.IsLockedOut)
                {
                    _logger.LogWarning("User account locked out.");
                    return RedirectToPage("./Lockout");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                    return Page();
                }
            }

            // If we got this far, something failed, redisplay form
            return Page();
        }
    }
}

SecuritySite/Pages/Account/Edit/Features.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SecuritySite.Models;
using SecuritySite.Services;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace SecuritySite.Pages.Account.edit
{
        [Authorize]
    public class FeaturesModel : PageModel
    {
        AccountUpdateService _update { get;set; }
        public AccountQueryService _query { get; set; }
        public FeaturesModel(AccountQueryService query, AccountUpdateService update) 
        {
            _update = update;
            _query = query;
        }

        [BindProperty(SupportsGet = true)]
        public int accountId { get; set; }
        public MonitoredAccount account { get; set; }
        public List<AccountFeature> accountFeatures { get; set; }
        public List<AccountFeature> availableFeatures { get; set; }
        public List<AccountFeature> basePlans { get;set; }
        public IActionResult OnGet()
        {
            try
            {
                if (_query.VerifyOwner(User, _query.GetMonitoredAccount(accountId)))
                {
                    account = _query.GetMonitoredAccount(accountId);
                }
            }
            catch
            {
                return RedirectToPage("error");
            }

            if (account == null)
            {
                return RedirectToPage("error");
            }
            else if (account.completed != true)
            {
                return RedirectToPage("/Account/new/Features", new {accountId = this.accountId});
            }
            accountFeatures = _query.GetFeatures(account.Features);
            availableFeatures = _query.FilterExisting( account.Features , _query.GetFeatures(account.commercial, false)).ToList();
            basePlans = _query.FilterExisting(account.Features, _query.GetFeatures(true)).ToList();

            return Page();
        }
        [BindProperty]
        public string test { get; set; }
        [BindProperty]
        public List<string> selectedFeatures { get; set; }
        public void OnPost()
        {

        }

        [BindProperty]
        public string RemoveCode { get; set; }
        public IActionResult OnPostRemoveFeature()
        {
            if (_query.VerifyOwner(User, _query.GetMonitoredAccount(accountId)))
            {
                account = _query.GetMonitoredAccount(accountId);
            }
            if (account == null)
            {
                return RedirectToPage("error");
            }
            else if (account.completed != true)
            {
                return RedirectToPage("/Account/new/Features", new { accountId = this.accountId });
            }

            AccountFeature feature = _query.GetFeature(RemoveCode);
            _update.remove_AccountFeature(account, feature);

            accountFeatures = _query.GetFeatures(account.Features);
            availableFeatures = _query.GetFeatures(account.commercial, false).ToList();
            basePlans = _query.FilterExisting(account.Features, _query.GetFeatures(true)).ToList();
            return Page();
            

        }
        [BindProperty]
        public List<string> addFeatures { get; set; }
        int x = 929;
        public IActionResult OnPostAddFeature()
        {
            if (_query.VerifyOwner(User, _query.GetMonitoredAccount(accountId)))
            {
                account = _query.GetMonitoredAccount(accountId);
            }
            if (account == null)
            {
                return RedirectToPage("error");
            }
            else if (account.completed != true)
            {
                return RedirectToPage("/Account/new/Features", new { accountId = this.accountId });
            }
            List<AccountFeature> features = _query.GetFeatures(addFeatures).ToList();

            foreach (AccountFeature feature in features)
            {
                if (feature == null) continue;
                if (feature.BasePlan)
                {
                    var oldPlan = _query.GetBasePlan(account);
                    _update.change_BasePlan(account, oldPlan, feature);

                    accountFeatures = _query.GetFeatures(account.Features);
                    availableFeatures = _query.FilterExisting(account.Features, _query.GetFeatures(account.commercial, false)).ToList();
                    basePlans = _query.FilterExisting(account.Features, _query.GetFeatures(true)).ToList();


                    return Page();
                }
            }
            _update.add_Features(account, addFeatures);

            accountFeatures = _query.GetFeatures(account.Features);
            availableFeatures = _query.FilterExisting(account.Features, _query.GetFeatures(account.commercial, false)).ToList();
            basePlans = _query.FilterExisting(account.Features, _query.GetFeatures(true)).ToList();
            return Page();
        }
    }
}

SecuritySite/Pages/Account/Edit/Location.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Identity.Client;
using SecuritySite.Models;
using SecuritySite.Services;

namespace SecuritySite.Pages.Account.Edit
{
    [Authorize]
    public class LocationModel : PageModel
    {
        public AccountQueryService _query { get; }
        public LocationModel(AccountQueryService query) 
        { 
         _query = query;
        }
        [BindProperty(SupportsGet =true)]
        public int id { get; set; }
        public MonitoredAccount LocationInfo { get; set; }
        public IActionResult OnGet()
        {
            try
            {
                if (_query.VerifyOwner(User, _query.GetMonitoredAccount(id)))
                {
                    LocationInfo = _query.GetMonitoredAccount(id);
                }
            }
            catch
            {
                return RedirectToPage("error");
            }

            if (LocationInfo == null)
            {
                return RedirectToPage("error");
            }
            else if (!LocationInfo.completed)
            {
                return RedirectToPage("/Account/new/Features", new { accountId = LocationInfo.MonitoredAccountId });
            }
            return Page();
        }
    }
}

SecuritySite/Pages/Account/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SecuritySite.Data;
using SecuritySite.Migrations;
using SecuritySite.Models;
using SecuritySite.Services;
using System.Net.Http.Headers;
using System.Security.Claims;

namespace SecuritySite.Pages.Account
{
    [Authorize]
    public class IndexModel : PageModel
    {
        public AccountQueryService _query { get; set; }
        public AccountUpdateService _update { get; set; }
        public IndexModel(AccountQueryService query, UserManager<ApplicationUser> users, AccountUpdateService update)
        {
            _query = query;
            _update = update;
        }
        public List<MonitoredAccount> MonitoredAccounts { get; set; } = new List<MonitoredAccount>();

        [BindProperty]
        public AccountInfo accountInfo { get; set; }
        public string PageView {  get; set; }
        public object pageModel { get;set; }
        public void OnGet()
        {
            var id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string guid = _query.GetAccountGuid(id);

            MonitoredAccounts = _query.GetMonitoredAccounts(guid).ToList();
            foreach(var monitoredAccount in MonitoredAccounts)
            {
                _update.update_AccountPrice(monitoredAccount);
            }
            if (!_query.GetAccountInfo(id).Completed())
            {
                PageView = "/Pages/Account/Info/_Overview.cshtml";
                pageModel = _query.GetAccountInfo(id);
            }
            else
            {
                PageView = "/Pages/Account/Info/_Locations.cshtml";
                pageModel = _query.GetMonitoredAccounts(guid).ToList();
            }
        }
        private AccountInfo account { get;set; }
        public PartialViewResult OnGetPageView(int id)
        {


            switch (id)
            {
                case 0: {
                        //List<MonitoredAccount> accounts = _query.GetMonitoredAccounts(User.FindFirstValue(ClaimTypes.NameIdentifier)).ToList();

                        account = _query.GetAccountInfo(User.FindFirstValue(ClaimTypes.NameIdentifier));
                        return Partial("Pages/Account/Info/_Overview.cshtml", account);
                    }
                case 1:
                    string guid = _query.GetAccountGuid(User.FindFirstValue(ClaimTypes.NameIdentifier));

                    List<MonitoredAccount> locations = _query.GetMonitoredAccounts(guid).ToList();


                    PageView = "/Pages/Account/Info/_Locations.cshtml";
                    pageModel = _query.GetMonitoredAccounts(guid).ToList();
                    return Partial("Pages/Account/Info/_Locations.cshtml", locations);
                case 2:
                    return Partial("Pages/Account/Info/_Invoicing.cshtml");
                case 3:
                    return Partial("Pages/Account/Info/_Notifications.cshtml");
                case 4:
                    return Partial("Pages/Account/Info/_Requests.cshtml");
                case 5:
                    return Partial("Pages/Account/Info/_Settings.cshtml");
                default:
                    return Partial("Pages/Account/Info/_Overview.cshtml");
            }

        }
        public void OnPostAccountInfo()
        {
            var id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _update.update_AccountInfo(id, accountInfo);
            PageView = "/Pages/Account/Info/_Overview.cshtml";
            pageModel = _query.GetAccountInfo(id);
        }
    }
}

SecuritySite/Pages/Account/Edit/Features.cshtml
@page "{accountId}"
@model SecuritySite.Pages.Account.edit.FeaturesModel
@{
}
<div class="new-features-inputs">

    <div class="features-container">
        <h2>Current Plans</h2>
        <p>Listed below is your current base plan followed by additional account features included.</p>
        <br/>
        @foreach (var feature in Model.accountFeatures)
        {
            <div class="account-addon-card">
                <p>@feature.FeatureName</p>
                <p>@feature.Price</p>
                <p>@feature.Description</p>
                <form asp-page="Features">
                    <input type="hidden" asp-for="RemoveCode" value="@feature.Code" />
                    <input type="hidden" asp-for="accountId" value="@Model.accountId" />
                    @if (!feature.BasePlan)
                    {
                        <button type="submit" asp-page-handler="RemoveFeature">Remove</button>
                    }
                </form>
            </div>
        }

    </div>






<div class="extra-features-container">
    <h1>Additional Features</h1>
        <p>Listed below are features which may be enabled to your plan.</p>
        <br />
    <form asp-page="Features">
        <input type="hidden" asp-for="accountId" value="@Model.accountId" />
        @foreach (var feature in Model.availableFeatures)
        {
                <div class="addon-features">
                <p>@feature.FeatureName</p>
                <p>@feature.Description</p>
                <p>@feature.Price</p>
                <select name="addFeatures" id="selectedFeatures">
                    <option value="">No</option>
                    <option value="@feature.Code">Add</option>
                </select>
            </div>
        }

        <button type="submit" asp-page-handler="AddFeature">Add Features</button>
    </form>

</div>

<div>
    <h1>Change Base Plan</h1>
        <p>Changing your base plan will remove all added features when switching between a residential location and a commercial location, please be sure to add the features that you would like after changing your plan.</p>
        <br />
    <form asp-page="Features">
        <input type="hidden" asp-for="accountId" value="@Model.accountId" />

        <div class="radio-grid">
            @foreach (var plan in Model.basePlans)
            {
                    if (Model.account.Features.Contains(plan.Code))
                        continue;

                <div>
                    <p class="same-line">@plan.FeatureName</p>
                    @(Html.RadioButtonFor(model => model.addFeatures, plan.Code))
                </div>

                <div>
                    @plan.Description
                </div>

                <div>
                    $@(plan.Price) Monthly
                </div>

            }
        </div>
        <button type="submit" asp-page-handler="AddFeature">Update Plan</button>
    </form>

</div>
</div>

SecuritySite/Pages/Account/Edit/Location.cshtml
@page "{id}"
@model SecuritySite.Pages.Account.Edit.LocationModel
@{
}
<div class="new-location-inputs">
@if (Model.LocationInfo.deleted)
{
    <p>Request has been made to delete this account.</p>
}
<h1>Account Info</h1>
    @if (Model.LocationInfo.commercial)
    {
        <h2 class="deblue">Commercial Property</h2>
    }
    else
    {
        <h2 class="deblue">Residential Property</h2>
    }

    @if (Model.LocationInfo.accepted)
    {
        <h2 class="blue">This account and changes has been approved by Voltic</h2>
    }
    else
    {
        <h2 class="redish">This account or changes made has not yet been approved by Voltic, please contact Voltic to enable/update your monitoring service.</h2>
    }

<form asp-page="Location" method="post" class="new-location-form">
    @Html.AntiForgeryToken()
    <label asp-for="LocationInfo.locationName">Location Name:</label>
    <input asp-for="LocationInfo.locationName" />
    <span asp-validation-for="LocationInfo.locationName"></span>
    <br />

    <label asp-for="LocationInfo.alarmPassword">Alarm Password:</label>
    <input asp-for="LocationInfo.alarmPassword" />
    <span asp-validation-for="LocationInfo.alarmPassword"></span>
    <br />

    <label asp-for="LocationInfo.durressCode">Durress Password:</label>
    <input asp-for="LocationInfo.durressCode" />
    <span asp-validation-for="LocationInfo.durressCode"></span>
    <br />

    <label asp-for="LocationInfo.emergencyContact">Emergency Contact:</label>
    <input asp-for="LocationInfo.emergencyContact" />
    <span asp-validation-for="LocationInfo.emergencyContact"></span>
    <br />

    <label asp-for="LocationInfo.emergencyContactPhoneNumber">Emergency Contact Phone Number:</label>
    <input asp-for="LocationInfo.emergencyContactPhoneNumber" />
    <span asp-validation-for="LocationInfo.emergencyContactPhoneNumber"></span>
    <br />

    <label asp-for="LocationInfo.address">Location Address:</label>
    <input asp-for="LocationInfo.address" />
    <span asp-validation-for="LocationInfo.address"></span>
    <br />

    <label asp-for="LocationInfo.city">City:</label>
    <input asp-for="LocationInfo.city" />
    <span asp-validation-for="LocationInfo.city"></span>
    <br />

    <label asp-for="LocationInfo.county">County:</label>
    <input asp-for="LocationInfo.county" />
    <span asp-validation-for="LocationInfo.county"></span>
    <br />

    <label asp-for="LocationInfo.state">State:</label>
    <input asp-for="LocationInfo.state" />
    <span asp-validation-for="LocationInfo.state"></span>
    <br />

    <label asp-for="LocationInfo.zipcode">Zip/Postal Code</label>
    <input asp-for="LocationInfo.zipcode" />
    <span asp-validation-for="LocationInfo.zipcode"></span>
    <br />

    <label asp-for="LocationInfo.installerCode">Installer Code</label>
    <input asp-for="LocationInfo.installerCode" />
    <br />
    <label asp-for="LocationInfo.additionalInfo">Additional Info</label>
    <textarea asp-for="LocationInfo.additionalInfo"></textarea><br/>

    <button type="submit">Update Info</button>
</form>

        <h2 class="deblue">$@(Model.LocationInfo.MonthlyCost) Monthly</h2>

        <p>Last Updated: @Model.LocationInfo.lastUpdated.ToShortDateString()</p>
        <p>Created on: @Model.LocationInfo.created.ToShortDateString()</p>

    <h3><a href="/account/edit/features/@Model.LocationInfo.MonitoredAccountId">View Account Features</a></h3>

    <br />
    <a href="/Account/remove/location/@Model.LocationInfo.MonitoredAccountId">Delete Account</a>
</div>